### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by andOlga** [07th-mod/umineko-hane-ons#1]
There are several things to be done before this mod is properly advertised as part of the 07th-Mod experience and made available to the general public through our installer. This is a list to remind myself and others of the things that are remaining before that can be done:

- [x] Finish translating and playtesting the mod
- [x] Package the mod as a zip file
- [x] Create a logo for the installer button
- [x] Add OS detection to the installer that will block installation of this mod on OS X and Linux, as this game/mod is Windows-only.
- [x] Figure out how to do path detection for Hane -- or whether to even do it in the first place. The game executable is named `うみねこのなく頃に羽.exe`, but there is no guarantee that this name is actually preserved.
- [x] Create a wiki page for Hane describing both the automatic and manual installation processes, as well as requirements for the patch to work.
